export const categories = [
  {
    name: "Appetizer",
    image: "https://picsum.photos/200/300",
    link: "/appetizer",
  },
  {
    name: "Bakery",
    image: "https://picsum.photos/200/301",
    link: "/bakery",
  },
  {
    name: "Beverages",
    image: "https://picsum.photos/200/302",
    link: "/beverages",
  },
  {
    name: "Desserts",
    image: "https://picsum.photos/200/303",
    link: "/desserts",
  },
  {
    name: "Dinner",
    image: "https://picsum.photos/200/304",
    link: "/dinner",
  },
  {
    name: "Lunch",
    image: "https://picsum.photos/200/305",
    link: "/lunch",
  },
  {
    name: "Salad",
    image: "https://picsum.photos/200/306",
    link: "/salad",
  },
];

export const newDish = [
  {
    id: 1,
    image: "https://picsum.photos/400/206",
    title: "Thai Basil Chicken",
    description:
      "Stir-fried chicken with Thai basil, chilies, and garlic, served with steamed jasmine rice.",
    cookingTime: "30 min",
    serving: 4,
  },
  {
    id: 2,
    image: "https://picsum.photos/400/207",
    title: "Creamy Mushroom Pasta",
    description:
      "Fettuccine tossed in a creamy mushroom sauce, topped with parmesan cheese and fresh parsley.",
    cookingTime: "25 min",
    serving: 2,
  },
  {
    id: 3,
    image: "https://picsum.photos/400/208",
    title: "Japanese Teriyaki Salmon",
    description:
      "Grilled salmon fillet glazed with a sweet and savory teriyaki sauce, served with steamed bok choy.",
    cookingTime: "20 min",
    serving: 2,
  },
  {
    id: 4,
    image: "https://picsum.photos/400/209",
    title: "Indian Butter Chicken",
    description:
      "Marinated chicken cooked in a rich butter tomato sauce, served with basmati rice and naan bread.",
    cookingTime: "40 min",
    serving: 4,
  },
  {
    id: 5,
    image: "https://picsum.photos/400/210",
    title: "Korean BBQ Beef",
    description:
      "Grilled beef short ribs marinated in a sweet and spicy Korean BBQ sauce, served with steamed kimchi.",
    cookingTime: "30 min",
    serving: 4,
  },
  {
    id: 6,
    image: "https://picsum.photos/400/211",
    title: "Vegan Black Bean Chili",
    description:
      "A hearty and flavorful vegan chili made with black beans, sweet potatoes, and a blend of spices.",
    cookingTime: "45 min",
    serving: 6,
  },
  {
    id: 7,
    image: "https://picsum.photos/400/212",
    title: "Roasted Vegetable Salad",
    description:
      "A colorful salad made with roasted vegetables such as sweet potatoes, Brussels sprouts, and cauliflower, tossed with a citrus vinaigrette.",
    cookingTime: "30 min",
    serving: 4,
  },
  {
    id: 8,
    image: "https://picsum.photos/400/213",
    title: "Grilled Chicken Caesar Salad",
    description:
      "A classic Caesar salad made with grilled chicken, romaine lettuce, croutons, and parmesan cheese, tossed with a tangy Caesar dressing.",
    cookingTime: "20 min",
    serving: 2,
  },
  {
    id: 9,
    image: "https://picsum.photos/400/214",
    title: "Creamy Tomato Soup",
    description:
      "A comforting and creamy tomato soup made with fresh tomatoes and herbs, served with a side of crusty bread.",
    cookingTime: "25 min",
    serving: 4,
  },
];

export const mockIngredients = [
  {
    vegetables: [
      { id: "1", name: "Carrot" },
      { id: "2", name: "Lettuce" },
      { id: "3", name: "Spinach" },
      { id: "4", name: "Bell Pepper" },
      { id: "5", name: "Onion" },
      { id: "6", name: "Tomato" },
      { id: "7", name: "Corn" },
      { id: "8", name: "Asparagus" },
      { id: "9", name: "Radish" },
      { id: "10", name: "Lotus Root" },
      { id: "11", name: "Cucumber" },
      { id: "12", name: "Zucchini" },
      { id: "13", name: "Eggplant" },
      { id: "14", name: "Okra" },
      { id: "15", name: "Green Onion" },
      { id: "16", name: "Garlic" },
      { id: "17", name: "Mushroom" },
      { id: "18", name: "Celery" },
      { id: "19", name: "Beet" },
      { id: "20", name: "Potato" },
      { id: "21", name: "Sweet Potato" },
      { id: "22", name: "Broccoli" },
      { id: "23", name: "Cauliflower" },
      { id: "24", name: "Brussels Sprouts" },
      { id: "25", name: "Leek" },
    ],
  },
  {
    meats: [
      { id: "1", name: "Chicken" },
      { id: "2", name: "Beef" },
      { id: "3", name: "Pork" },
      { id: "4", name: "Sheep" },
      { id: "5", name: "Duck" },
      { id: "6", name: "Goose" },
      { id: "7", name: "Deer" },
      { id: "8", name: "Wild Boar" },
      { id: "9", name: "Rabbit" },
      { id: "10", name: "Quail" },
      { id: "11", name: "Turkey" },
      { id: "12", name: "Shrimp" },
      { id: "13", name: "Crab" },
      { id: "14", name: "Fish" },
      { id: "15", name: "Octopus" },
      { id: "16", name: "Squid" },
      { id: "17", name: "Lobster" },
      { id: "18", name: "Crab" },
      { id: "19", name: "Prawn" },
      { id: "20", name: "Oyster" },
      { id: "21", name: "Salmon" },
      { id: "22", name: "Tuna" },
      { id: "23", name: "Swordfish" },
      { id: "24", name: "Mackerel" },
      { id: "25", name: "Snail" },
    ],
  },
  {
    fruits: [
      { id: "1", name: "Banana" },
      { id: "2", name: "Apple" },
      { id: "3", name: "Grape" },
      { id: "4", name: "Orange" },
      { id: "5", name: "Kiwi" },
      { id: "6", name: "Avocado" },
      { id: "7", name: "Plum" },
      { id: "8", name: "Dragon Fruit" },
      { id: "9", name: "Pineapple" },
      { id: "10", name: "Mango" },
      { id: "11", name: "Strawberry" },
      { id: "12", name: "Blueberry" },
      { id: "13", name: "Raspberry" },
      { id: "14", name: "Blackberry" },
      { id: "15", name: "Watermelon" },
      { id: "16", name: "Peach" },
      { id: "17", name: "Pear" },
      { id: "18", name: "Grapefruit" },
      { id: "19", name: "Lemon" },
      { id: "20", name: "Orange" },
      { id: "21", name: "Lychee" },
      { id: "22", name: "Coconut" },
      { id: "23", name: "Pomegranate" },
      { id: "24", name: "Tangerine" },
      { id: "25", name: "Papaya" },
    ],
  },
];
